name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - goodixtls

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgusb-dev libgirepository1.0-dev libnss3-dev libgudev-1.0-dev libpixman-1-dev libcairo2-dev libopencv-dev
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          setup-options: --prefix /usr/ --buildtype=release
          options: --verbose
          meson-version: 0.63.3
          ninja-version: 1.10.2
